export const ATTRIBUTE_SYNCRO_TREES = '[name ^= "attribute_group_tree"], [name ^= "attribute_tree"], [name ^= "duty_attribute_tree"], [name ^= "attribute_product_tree"], [name ^= "deduplicate_tree"], [name ^= "detach_tree"]';
export const ATTRIBUTE_GROUP_TREE = '[name ^= "attribute_group_tree"]';
export const CATEGORY_TREE = '[name ^= "category_tree"]';
export const CATEGORY_ATTRIBUTE_TREE = '[name ^= "category_attribute_tree"]';
export const DUTY_ATTRIBUTE_TREE = '[name ^= "duty_attribute_tree"]';
export const ATTRIBUTE_TREE = '[name ^= "attribute_tree"]';
export const ATTRIBUTE_PRODUCT_TREE = '[name ^= "attribute_product_tree"]';
export const PRODUCT_TREE = '[name ^= "product_tree"]';
export const GROUP_CHECK_TREE = '[name ^= "deduplicate_tree"], [name ^= "detach_tree"]';
export const CATEGORY_CHECK_TREE = '[name ^= "category_check_tree"]';
export const CATEGORY_SYNCRO_TREES = '[name ^= "category_check_tree"], [name ^= "category_tree"]';
export const smartScroll = 'input[name = "attributico_smart_scroll"]:checkbox';